[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_SUPABASE_URL = "https://ixroiuhpvsljxeynfrqz.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4cm9pdWhwdnNsanhleW5mcnF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzUyMTMsImV4cCI6MjA2OTY1MTIxM30.GggeoRijune6o5eQWQDODw5QnBfd6d1FxWKu7R8Q5FA"
  REACT_APP_MODE = "supabase-only"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200